
;; ******************************************************************************
;; Copyright (C) 2016 Push Technology Ltd.
;;
;; Licensed under the Apache License, Version 2.0 (the "License");
;; you may not use this file except in compliance with the License.
;; You may obtain a copy of the License at
;; http://www.apache.org/licenses/LICENSE-2.0
;;
;; Unless required by applicable law or agreed to in writing, software
;; distributed under the License is distributed on an "AS IS" BASIS,
;; WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
;; See the License for the specific language governing permissions and
;; limitations under the License.
;; *******************************************************************************

(ns ^:figwheel-always taxi.core
    (:require [taxi.communication :as d]
              [taxi.controller :as controller]
              [taxi.passenger :as passenger]
              [taxi.taxi :as taxi]
              [taxi.grid-rendering :as rendering]
              [taxi.navigation :as navigation]
              [clojure.string :refer (join)]
              [cljs.core.async :refer [put! chan <!]])
    (:require-macros [cljs.core.async.macros :refer [go go-loop]]))

(enable-console-print!)
(js/diffusion.log "debug")

;; The connection options for the Reappt server
;; The host, port and security are configured from values set by the js/endpoint.js resource
;; This resource is generated by the Ring handler
(def connection-options #js {:host (.-reapptHost js/window)
                             :port (.-reapptPort js/window)
                             :secure (.-reapptSecure js/window)
                             :reconnect false
                             :principal "taxi"
                             :credentials "taxi"})

(defonce app-state (atom {}))

(defn- new-state
  [old-state error new-session]

  (if-let [old-session (:session old-state)]
    (.close old-session))

  ;; I'd like to pass this context around using dynamic bindings, but
  ;; cljs doesn't (yet?) allow that
  ;; https://groups.google.com/forum/#!topic/clojure/xtxRVuSOLg4
  {:session new-session
   :error error
   })

(defn restart []

  ; Use a single session per client. We replace it on page load.
  (let [errors (chan)
        connection (chan)
        error (fn [& s] (put! errors (join \space s)))]
    (d/connect connection error connection-options)

    (go-loop [e (<! errors)]
      (when e
        (js/console.error e)
        recur (<! errors)))

    (go
     (swap! app-state new-state error (<! connection))
     (and
      (<! (controller/init app-state))
      (<! (taxi/init app-state))
      (passenger/init app-state)

      (navigation/render app-state)

       ))))

(restart)
